### ISSUE TITLE
in my opinion the Ore Eater version 2 (aka the older version) is not fast enough (by witch i mean that it cant keep up with me when i have hermes boots(sorry if i misspell))

### ISSUE THREAD

**Issue by Kirito14234** [srtsnlt/AutoStacker#3]
in my opinion the Ore Eater version 2 (aka the older version) is not fast enough (by withc i mean that it cant keep up with me when i have hermes boots(sorry if i misspell)) so maybe make it follow faster?

**Comment by Kirito14234** [comment]
well I suppose that it should have some issues . . . since it is pretty good for the stage at witch you can (currently) get it

**Comment by srtsnlt** [comment]
I update Ore Eater Ver.2 in 0.3.17.
The AI is based on "Ore Eater", and your ploblem is solved.

Sorry to late!

**Comment by Kirito14234** [comment]
No problem :-) thx for the fix (haven't played in a while so haven't tested it yet but I trust you.
